all:
  children:
    ubuntu_servers:
      hosts:
        swartninja:
          ansible_host: 192.168.1.201
        blackbeard:
          ansible_host: 192.168.1.202
      vars:
        ansible_port: '{{ ssh_port }}'
        ansible_user: '{{ ssh_user }}'
        ansible_ssh_private_key_file: '{{ ssh_private_key_file_path }}'
        ansible_become_password: '{{ ssh_password }}'
    pihole_servers:
      hosts:
        pi_hole:
          ansible_host: 192.168.1.5
        pi_hole_fallback:
          ansible_host: 192.168.1.4
          ansible_user: '{{ ssh_user }}'
          ansible_ssh_private_key_file: '{{ ssh_private_key_file_path }}'