---
# command: ansible-playbook ~/ansible-homelab/playbooks/apt.yml --ask-vault-pass
#

- name: update servers
  hosts: ubuntu_servers
  become: yes

  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'
